
package vistas;

import accesoAdatos.MesaData;
import accesoAdatos.PedidoData;
import accesoAdatos.PedidoProductoData;
import accesoAdatos.ProductoData;
import entidades.Mesa;
import entidades.Pedido;
import entidades.PedidoProducto;
import entidades.Producto;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class AgregarProductos extends javax.swing.JInternalFrame {

    private MesaData md;
    private ProductoData prodData;
    private PedidoProductoData ppd;
    private PedidoData pd;
    private DefaultTableModel modelo = new DefaultTableModel();
   
    FondoPanel fondo = new FondoPanel();
    public AgregarProductos() {
        initComponents();
        md= new MesaData();
        prodData= new ProductoData();
        ppd= new PedidoProductoData();
        pd= new PedidoData();
        llenarCombo1();
        llenarCombo2();
        armarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jBSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jBAgregarProductos = new javax.swing.JButton();
        jCBProducto = new javax.swing.JComboBox<>();
        jTFCantidad = new javax.swing.JTextField();
        jCBMesa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setText("Salir");
        jBSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(153, 255, 255)));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 660, 80, -1));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 460, 150));

        jBAgregarProductos.setText("Agregar Productos");
        jBAgregarProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(153, 255, 255)));
        jBAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProductosActionPerformed(evt);
            }
        });
        jPanel1.add(jBAgregarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 120, -1));

        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jCBProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 260, -1));

        jTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 260, -1));

        jPanel1.add(jCBMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 260, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elija una mesa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Productos Al Pedido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/agregar pedido.jpg"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        try{
        Mesa m= (Mesa) jCBMesa.getSelectedItem();
        int cantidad= Integer.parseInt(jTFCantidad.getText());
        Producto p= (Producto)jCBProducto.getSelectedItem();
        int idPedido=pd.pedidoXIdMesa(m);
        //Capturo los datos los pongo en la tabla
        modelo.addRow(new Object[]{idPedido, p.getIdProducto(), p.getNombre(), cantidad, p.getPrecio()});
        //Limpio los campos para seguir agregando productos
        jTFCantidad.setText("");
        jCBMesa.setSelectedItem(null);
        jCBProducto.setSelectedItem(null);
        } catch(NullPointerException nc){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto, cantidad  idPedido no pueden ser nulos");
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Los campos no deben ser nulos");
        }
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jBAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProductosActionPerformed
        try{
        //Se agregan todos los productos de la tabla
        for(int i=0; i<modelo.getRowCount(); i++){
            Integer idPedido= (Integer)( modelo.getValueAt(i, 0));
            Integer idProducto= (Integer) modelo.getValueAt(i, 1);
            Integer cantidad= (Integer)modelo.getValueAt(i, 3);
            Pedido p= pd.buscarPedidoXid(idPedido);
            
            Producto pr= prodData.buscarProductoPorId(idProducto);
            
            PedidoProducto pedProd= new PedidoProducto(pr, p, cantidad);
            ppd.iniciarPedidoProducto(pedProd);   
        }
        //Limpio la tabla
        limpiarTabla();
        }catch(NullPointerException nc){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
        }
    }//GEN-LAST:event_jBAgregarProductosActionPerformed

    private void jTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCantidadKeyTyped

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarProductos;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Mesa> jCBMesa;
    private javax.swing.JComboBox<Producto> jCBProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
 public void llenarCombo1() {
        jCBMesa.addItem(null);
        ArrayList<Mesa> lista = md.mesasOcupadas();
        for (Mesa m : lista) {
            jCBMesa.addItem(m);
        }
    }
 
 public void llenarCombo2(){
        jCBProducto.addItem(null);
        ArrayList<Producto> lista= prodData.listarProductos();
        for (Producto p: lista){
            jCBProducto.addItem(p);
        }
    }
 
  public void armarCabecera(){
        modelo.addColumn("Numero de Mesa");
        modelo.addColumn("IdProducto");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        jTabla.setModel(modelo);
    }
  
   public void limpiarTabla() {
        int f = jTabla.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    class FondoPanel extends JPanel
    {
    private  Image imagen;
    
    @Override
    public void paint(Graphics g)
    {
     imagen = new ImageIcon(getClass().getResource("/Img/imag-interF.jpg")).getImage();
    
     g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
    setOpaque(false);
    super.paint(g);
    }
    
    }
   
   
   
}
