/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import accesoAdatos.MesaData;
import accesoAdatos.PedidoData;
import accesoAdatos.PedidoProductoData;
import accesoAdatos.ProductoData;
import entidades.Mesa;
import entidades.Pedido;
import entidades.PedidoProducto;
import entidades.Producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mariana
 */
public class AgregarProductos extends javax.swing.JInternalFrame {

    private MesaData md;
    private ProductoData prodData;
    private PedidoProductoData ppd;
    private PedidoData pd;
    private DefaultTableModel modelo = new DefaultTableModel();
    public AgregarProductos() {
        initComponents();
        md= new MesaData();
        prodData= new ProductoData();
        ppd= new PedidoProductoData();
        pd= new PedidoData();
        llenarCombo1();
        llenarCombo2();
        armarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBMesa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jBAgregarProductos = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Productos Al Pedido");

        jLabel2.setText("Elija una mesa:");

        jLabel3.setText("Producto:");

        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jBAgregarProductos.setText("Agregar Productos");
        jBAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProductosActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad");

        jTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCBMesa, 0, 233, Short.MAX_VALUE)
                                    .addComponent(jCBProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFCantidad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAgregarProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalir)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarProductos)
                    .addComponent(jBSalir))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        try{
        Mesa m= (Mesa) jCBMesa.getSelectedItem();
        int cantidad= Integer.parseInt(jTFCantidad.getText());
        Producto p= (Producto)jCBProducto.getSelectedItem();
        int idPedido=pd.pedidoXIdMesa(m);
        //Capturo los datos los pongo en la tabla
        modelo.addRow(new Object[]{idPedido, p.getIdProducto(), p.getNombre(), cantidad, p.getPrecio()});
        //Limpio los campos para seguir agregando productos
        jTFCantidad.setText("");
        jCBMesa.setSelectedItem(null);
        jCBProducto.setSelectedItem(null);
        } catch(NullPointerException nc){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto, cantidad  idPedido no pueden ser nulos");
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Los campos no deben ser nulos");
        }
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jBAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProductosActionPerformed
        try{
        //Se agregan todos los productos de la tabla
        for(int i=0; i<modelo.getRowCount(); i++){
            Integer idPedido= (Integer)( modelo.getValueAt(i, 0));
            Integer idProducto= (Integer) modelo.getValueAt(i, 1);
            Integer cantidad= (Integer)modelo.getValueAt(i, 3);
            Pedido p= pd.buscarPedidoXid(idPedido);
            
            Producto pr= prodData.buscarProductoPorId(idProducto);
            
            PedidoProducto pedProd= new PedidoProducto(pr, p, cantidad);
            ppd.iniciarPedidoProducto(pedProd);   
        }
        //Limpio la tabla
        limpiarTabla();
        }catch(NullPointerException nc){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
        }
    }//GEN-LAST:event_jBAgregarProductosActionPerformed

    private void jTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCantidadKeyTyped

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarProductos;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Mesa> jCBMesa;
    private javax.swing.JComboBox<Producto> jCBProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
 public void llenarCombo1() {
        jCBMesa.addItem(null);
        ArrayList<Mesa> lista = md.mesasOcupadas();
        for (Mesa m : lista) {
            jCBMesa.addItem(m);
        }
    }
 
 public void llenarCombo2(){
        jCBProducto.addItem(null);
        ArrayList<Producto> lista= prodData.listarProductos();
        for (Producto p: lista){
            jCBProducto.addItem(p);
        }
    }
 
  public void armarCabecera(){
        modelo.addColumn("Numero de Mesa");
        modelo.addColumn("IdProducto");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        jTabla.setModel(modelo);
    }
  
   public void limpiarTabla() {
        int f = jTabla.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

}
