/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author EXO
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        dpPanel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmProductos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmMesas = new javax.swing.JMenuItem();
        jmEstadosP = new javax.swing.JMenu();
        jmEstadoP = new javax.swing.JMenuItem();
        jmListaPr = new javax.swing.JMenuItem();
        jmDisponibilidad = new javax.swing.JMenuItem();
        jmFacturacion = new javax.swing.JMenuItem();
        jmIniciarP = new javax.swing.JMenu();
        jmIniciarPed = new javax.swing.JMenuItem();
        jmFinalizarP = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpPanel.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/234fondo.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dpPanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpPanelLayout = new javax.swing.GroupLayout(dpPanel);
        dpPanel.setLayout(dpPanelLayout);
        dpPanelLayout.setHorizontalGroup(
            dpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dpPanelLayout.setVerticalGroup(
            dpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(155, 32768));

        jmProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/blanco 1.png"))); // NOI18N
        jmProductos.setText("Administracion");
        jmProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmProductos.setMaximumSize(new java.awt.Dimension(130, 32769));
        jmProductos.setPreferredSize(new java.awt.Dimension(146, 41));
        jmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProductosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmProductos.add(jMenuItem1);

        jmMesas.setText("Mesas");
        jmMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMesasActionPerformed(evt);
            }
        });
        jmProductos.add(jmMesas);

        jMenuBar1.add(jmProductos);

        jmEstadosP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/blanco 1.png"))); // NOI18N
        jmEstadosP.setText("Consultas");
        jmEstadosP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmEstadosP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmEstadosP.setMargin(new java.awt.Insets(0, 6, 3, 6));
        jmEstadosP.setMaximumSize(new java.awt.Dimension(136, 32773));
        jmEstadosP.setPreferredSize(new java.awt.Dimension(146, 41));

        jmEstadoP.setText("Estado de Pedidos");
        jmEstadoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstadoPActionPerformed(evt);
            }
        });
        jmEstadosP.add(jmEstadoP);

        jmListaPr.setText("Lista del Producto");
        jmListaPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaPrActionPerformed(evt);
            }
        });
        jmEstadosP.add(jmListaPr);

        jmDisponibilidad.setText("Disponibilidad de Mesa");
        jmDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDisponibilidadActionPerformed(evt);
            }
        });
        jmEstadosP.add(jmDisponibilidad);

        jmFacturacion.setText("Facturacion");
        jmFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFacturacionActionPerformed(evt);
            }
        });
        jmEstadosP.add(jmFacturacion);

        jMenuBar1.add(jmEstadosP);

        jmIniciarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/blanco 1.png"))); // NOI18N
        jmIniciarP.setText("Gestion");
        jmIniciarP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmIniciarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmIniciarP.setMaximumSize(new java.awt.Dimension(130, 32767));
        jmIniciarP.setMinimumSize(new java.awt.Dimension(125, 41));
        jmIniciarP.setPreferredSize(new java.awt.Dimension(125, 41));

        jmIniciarPed.setText("Iniciar Pedido");
        jmIniciarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIniciarPedActionPerformed(evt);
            }
        });
        jmIniciarP.add(jmIniciarPed);

        jmFinalizarP.setText("Finalizar Pedido");
        jmFinalizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFinalizarPActionPerformed(evt);
            }
        });
        jmIniciarP.add(jmFinalizarP);

        jMenuBar1.add(jmIniciarP);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEstadoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstadoPActionPerformed
   dpPanel.removeAll();
        dpPanel.repaint();
        VistasEstadoDePedidos vep = new VistasEstadoDePedidos();
        vep.setVisible(true);
        dpPanel.add(vep);
        dpPanel.moveToFront(vep);     
    }//GEN-LAST:event_jmEstadoPActionPerformed

    private void jmFinalizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFinalizarPActionPerformed
  dpPanel.removeAll();
        dpPanel.repaint();
        VistasFinalizarPedido vfp = new VistasFinalizarPedido();
        vfp.setVisible(true);
        dpPanel.add(vfp);
        dpPanel.moveToFront(vfp);    }//GEN-LAST:event_jmFinalizarPActionPerformed

    private void jmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProductosActionPerformed
        dpPanel.removeAll();
        dpPanel.repaint();
        VistasProducto vp = new VistasProducto();
        vp.setVisible(true);
        dpPanel.add(vp);
        dpPanel.moveToFront(vp);
        
        
    }//GEN-LAST:event_jmProductosActionPerformed

    private void jmMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMesasActionPerformed
         dpPanel.removeAll();
        dpPanel.repaint();
        VistasMesas vm = new VistasMesas();
        vm.setVisible(true);
        dpPanel.add(vm);
        dpPanel.moveToFront(vm);
        
    }//GEN-LAST:event_jmMesasActionPerformed

    private void jmListaPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaPrActionPerformed
       dpPanel.removeAll();
        dpPanel.repaint();
        VistasListaDeProducto vlp = new VistasListaDeProducto();
        vlp.setVisible(true);
        dpPanel.add(vlp);
        dpPanel.moveToFront(vlp);
    }//GEN-LAST:event_jmListaPrActionPerformed

    private void jmDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDisponibilidadActionPerformed
           dpPanel.removeAll();
        dpPanel.repaint();
        VistaDisponibilidadDeMesa vdm = new VistaDisponibilidadDeMesa();
        vdm.setVisible(true);
        dpPanel.add(vdm);
        dpPanel.moveToFront(vdm);
    }//GEN-LAST:event_jmDisponibilidadActionPerformed

    private void jmFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFacturacionActionPerformed
          dpPanel.removeAll();
        dpPanel.repaint();
        VistasFacturacion vf = new VistasFacturacion();
        vf.setVisible(true);
        dpPanel.add(vf);
        dpPanel.moveToFront(vf);
    }//GEN-LAST:event_jmFacturacionActionPerformed

    private void jmIniciarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIniciarPedActionPerformed
         dpPanel.removeAll();
        dpPanel.repaint();
        VistasIniciarPedido vip = new VistasIniciarPedido();
        vip.setVisible(true);
        dpPanel.add(vip);
        dpPanel.moveToFront(vip);
    }//GEN-LAST:event_jmIniciarPedActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       dpPanel.removeAll();
        dpPanel.repaint();
        VistasProducto vp = new VistasProducto();
        vp.setVisible(true);
        dpPanel.add(vp);
        dpPanel.moveToFront(vp);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmDisponibilidad;
    private javax.swing.JMenuItem jmEstadoP;
    private javax.swing.JMenu jmEstadosP;
    private javax.swing.JMenuItem jmFacturacion;
    private javax.swing.JMenuItem jmFinalizarP;
    private javax.swing.JMenu jmIniciarP;
    private javax.swing.JMenuItem jmIniciarPed;
    private javax.swing.JMenuItem jmListaPr;
    private javax.swing.JMenuItem jmMesas;
    private javax.swing.JMenu jmProductos;
    // End of variables declaration//GEN-END:variables
}
