
package vistas;

import accesoAdatos.ProductoData;
import entidades.Producto;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class VistasListaDeProducto extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo= new DefaultTableModel();
    FondoPanel fondo = new FondoPanel();
    public boolean isCellEditable(int f, int c){
        return false;
    }
   
    public VistasListaDeProducto() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jRBPorNombre = new javax.swing.JRadioButton();
        jRBTodos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTBuscarPorNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRBPorNombre.setBackground(new java.awt.Color(204, 204, 204));
        jRBPorNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRBPorNombre.setForeground(new java.awt.Color(255, 255, 255));
        jRBPorNombre.setText("Por Nombre");
        jRBPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPorNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jRBPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jRBTodos.setBackground(new java.awt.Color(204, 204, 204));
        jRBTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRBTodos.setForeground(new java.awt.Color(255, 255, 255));
        jRBTodos.setText("Todos ");
        jRBTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTodosActionPerformed(evt);
            }
        });
        jPanel1.add(jRBTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jTBuscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBuscarPorNombreActionPerformed(evt);
            }
        });
        jTBuscarPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarPorNombreKeyReleased(evt);
            }
        });
        jPanel1.add(jTBuscarPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 163, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escriba los primeros caracteres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProducto.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTableProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 385, 295));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, -1));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/producto.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -430, 1440, 1450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPorNombreActionPerformed
        jRBTodos.setEnabled(false);
        jTBuscarPorNombre.setEnabled(true);
    }//GEN-LAST:event_jRBPorNombreActionPerformed

    private void jRBTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTodosActionPerformed
        jRBPorNombre.setEnabled(false);
        jTBuscarPorNombre.setEnabled(false);
        cargarTodos();
                
    }//GEN-LAST:event_jRBTodosActionPerformed

    private void jTBuscarPorNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarPorNombreKeyReleased
        borrarFilas();
        ProductoData pd= new ProductoData();
        ArrayList<Producto> lista= new ArrayList<>();
        lista= pd.listarProductos();
        for(Producto prod: lista){
            if(prod.getNombre().startsWith(jTBuscarPorNombre.getText())){
                modelo.addRow(new Object[]{prod.getNombre(), prod.getIdProducto(), prod.getPrecio(), prod.getCantidad()});
            }
        }
    }//GEN-LAST:event_jTBuscarPorNombreKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        borrarFilas();
        jRBPorNombre.setEnabled(true);
        jRBTodos.setEnabled(true);
        jRBPorNombre.setSelected(false);
        jRBTodos.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTBuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBuscarPorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarPorNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBPorNombre;
    private javax.swing.JRadioButton jRBTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscarPorNombre;
    private javax.swing.JTable jTableProducto;
    // End of variables declaration//GEN-END:variables
public void armarCabecera(){
        modelo.addColumn("Nombre");
        modelo.addColumn("IdProducto");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jTableProducto.setModel(modelo);
    }
    public void borrarFilas(){
        int f= jTableProducto.getRowCount()-1;
        for (;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    public void cargarTodos(){
       borrarFilas();
        ProductoData pd= new ProductoData();
        ArrayList<Producto> lista= new ArrayList<>();
        lista= pd.listarProductos();
        
        for(Producto pr: lista){
            modelo.addRow(new Object[]{pr.getNombre(), pr.getIdProducto(), pr.getPrecio(), pr.getCantidad()});
        }
    }
    
       class FondoPanel extends JPanel
    {
    private  Image imagen;
    
    @Override
    public void paint(Graphics g)
    {
     imagen = new ImageIcon(getClass().getResource("/Img/imag-interF.jpg")).getImage();
    
     g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
    setOpaque(false);
    super.paint(g);
    }
    
    }
            
}
